"""Added summary fields to ResearchPaper

Revision ID: 9a9bd40cd362
Revises: 3ddefeb87c52
Create Date: 2023-12-15 23:22:33.408473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9bd40cd362'
down_revision = '3ddefeb87c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_findings', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('methodology', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('related_work', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_paper', schema=None) as batch_op:
        batch_op.drop_column('related_work')
        batch_op.drop_column('methodology')
        batch_op.drop_column('key_findings')

    # ### end Alembic commands ###
