"""Updated ResearchPaper model

Revision ID: a9342b10b8f1
Revises: 0f2ee8c31788
Create Date: 2023-12-15 03:18:26.863771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9342b10b8f1'
down_revision = '0f2ee8c31788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper')
    with op.batch_alter_table('research_paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('published_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pdf_link', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('webpage_link', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('categories', sa.String(length=200), nullable=True))
        batch_op.drop_column('abstract')
        batch_op.drop_column('references')
        batch_op.drop_column('citations')
        batch_op.drop_column('download_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_link', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('citations', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('references', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('abstract', sa.TEXT(), nullable=False))
        batch_op.drop_column('categories')
        batch_op.drop_column('webpage_link')
        batch_op.drop_column('pdf_link')
        batch_op.drop_column('comments')
        batch_op.drop_column('updated_date')
        batch_op.drop_column('published_date')
        batch_op.drop_column('authors')

    op.create_table('paper',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('abstract', sa.TEXT(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('references', sa.TEXT(), nullable=True),
    sa.Column('download_link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('citations', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
